apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wyz5oicpd-nodejs 
  janus-idp.io/tekton: wyz5oicpd-nodejs
  backstage.io/kubernetes-id: wyz5oicpd-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wyz5oicpd-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml